spring:
  application:
    name: user-ms
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userDB
      username: bookstore
      password: bookstore123
      authentication-database: admin

server:
  port: 8082